# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7ea8ca8f8d9e8ca92477e0e7876c32ac9d73d80a71630a288bbe22e283f29ef49fbfc509a110d9de6021d827f1cb6cac9d82410d0471e7316d522e6bba45743

test:
  secret_key_base: 8667a5514aa7ae2f4082f2b6ad4c0d87fea15b3ce28693fa241447f683b3fa1d8be9eeb1078a1f611478517f1ea1e2450c6f762df45d1e872467ffbbfafd6844

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
